# Generated by Django 6.0.7 on 2026-08-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_wishlist_options_alter_wishlist_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Customer Info'},
        ),
    ]
