# Generated by Django 6.0.7 on 2026-08-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_profile_image_profile_address_profile_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='photo',
        ),
    ]
