# Generated by Django 6.0.7 on 2026-08-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_rename_profile_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='image',
        ),
    ]
